
@api = https://iqbol-express-api.herokuapp.com
##get all posts
GET {{api}}/posts
#########

### add post
POST {{api}}/posts
Content-Type: application/json


{
    "id": 0,
    "content": "first POST",
    "likes":0,
    "isLiked":false
} 

### update posts
POST {{api}}/posts
Content-Type: application/json

{
    "id": 2,
    "content": "Ed Post",
    "likes":0,
    "isLiked":false
} 

###delete posts
DELETE {{api}}/posts/2
Content-Type: application/json

####like++
POST {{api}}/posts/1/likes

####like--
DELETE  {{api}}/posts/1/likes